---
  
web:
  listenAddress: :9191
  telemetryPath: /metrics
  timeout: 10s

db:
  user: admin
  password: password
  uri: http://localhost:8091
  timeout: 10s

log:
  level: info
  format: text

scrape:
  cluster: true
  node: true
  bucket: true
  xdcr: true